name: Norme, Compilation & Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Make simple libft
        run: make
      - name: Make bonus libft
        run: make bonus
      - name: Make full libft
        run: make full
      - name: Checkout Tester
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init
      # - name: Update Env
      #   run: sudo apt update && sudo apt upgrade -y
      - name: Install Progs for Tester
        run: sudo apt-get install -y bash diffutils python3 gcc clang build-essential && python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette
      - name: Tester Init
        run: cd war-machine && ./grademe.sh -u -m
      - name: Tester Execute
        run: cd war-machine && bash grademe.sh -u -m
      - name: Tester Deepthought
        run: cat war-machine/deepthought
#      - name: Is Valid ?
#        run: cat war-machine/deepthought | grep KO
      - name: Tester 2 Execute
        run: cd libftTester && sudo make a
      - name: Clean
        run: make fclean
